version: "3.8"
services:
  trazi-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes # Enable AOF persistence
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
